nmHoistingLimits: workspaces

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.13.0.cjs

packageExtensions:
  "@react-native/eslint-config@*":
    dependencies:
      typescript: "*"
  "@react-native/jest-preset@*":
    dependencies:
      "@babel/core": "^7.29.0"
  "babel-plugin-transform-flow-enums@*":
    dependencies:
      "@babel/core": "^7.29.0"
